name: Node.js CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
